
[manager]
ratio = [1,3,3]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
sort_reverse = false
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 250

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_filter = "lanczos3"
image_quality = 70
sixel_fraction = 15

[opener]
edit = [
	{ exec = 'nvim "$@"', block = true, for = "unix" },
	{ exec = 'code "%*"',    orphan = true, for = "windows" },
]
open = [
	{ exec = 'xdg-open "$@"', block = false, orphan = true,  desc = "Open", for = "linux" },
	{ exec = 'open "$@"',                 desc = "Open", for = "macos" },
	{ exec = 'start "%1"', orphan = true, desc = "Open", for = "windows" }
]
reveal = [
	{ exec = 'open -R "$1"',                       desc = "Reveal", for = "macos" },
	{ exec = 'explorer /select,%1', orphan = true, desc = "Reveal", for = "windows" },
	{ exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ exec = 'unar "$1"', desc = "Extract here", for = "unix" },
	{ exec = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
	{ exec = 'mpv "$@"', block = false, orphan = true, for = "unix" },
	{ exec = 'xdg-open "$@"', block = false, orphan = true, for = "unix" },
	{ exec = 'mpv "%1"', orphan = true, for = "windows" },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "text/*",  use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "application/zip",             use = [ "extract", "reveal" ] },
	{ mime = "application/gzip",            use = [ "extract", "reveal" ] },
	{ mime = "application/x-tar",           use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip",          use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip2",         use = [ "extract", "reveal" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
	{ mime = "application/x-rar",           use = [ "extract", "reveal" ] },

	{ mime = "*", use = [ "open", "play", "reveal" ] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5
